server:
  port: 80
spring:
  application:
    name: cloud-order-service
  zipkin:
    base-url: http://192.168.163.56:9411
  sleuth:
    sampler:
      probability: 1
eureka:
  client:
    #    注册加入EurekaServer
    register-with-eureka: true
    fetch-registry: true
    #    注册加入哪一个Eureka
    service-url:
      defaultZone: http://localhost:7001/eureka/,http://localhost:7002/eureka/
  instance:
    instance-id: consumer80
    hostname: consumer